// src/components/Redirecting.svelte
<script>
  import Loader from "./Loader.svelte";
</script>

<div
  style="position: fixed; top: 0; left: 0; right: 0; bottom: 0; display: flex; flex-direction: column; justify-content: center; align-items: center; background-color: #D6E3F8; z-index: 9999;"
>
  <h1>正在轉移陣地</h1>
  <p>請稍等片刻...</p>
  <Loader />
</div>

// frontend/src/components/Redirecting.vue
<template>
    <div
        style="position: fixed; top: 0; left: 0; right: 0; bottom: 0; display: flex; flex-direction: column; justify-content: center; align-items: center; background-color: #D6E3F8; z-index: 9999;">
        <h1>正在轉移陣地</h1>
        <p>請稍等片刻...</p>
        <Loader />
    </div>
</template>

<script setup lang="ts">
import Loader from './Loader.vue'
</script>


<style scoped>
/* No additional styles needed */
</style>
