// frontend/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import InputCard from './components/InputCard.vue'
import Loader from './components/Loader.vue'
import Result from './components/Result.vue'
import Layout from './layouts/Layout.vue'

// Props equivalent
interface Props {
  title?: string
  subtitle?: string
}

const props = withDefaults(defineProps<Props>(), {
  title: '估咩評論小扒手🫳',
  subtitle: 'GooMap Review Snatcher'
})

const searchStoreUrl = "/api/search"
const getReviewsUrl = "/api/reviews"

// Reactive state
const searchInputStr = ref("")
const selectedStore = ref<any>(null)
const pagesToFetch = ref(1)
const storeData = ref<any[]>([])
const reviews = ref<any[]>([])
const isLoading = ref(false)
const searchUUID = ref("")
const reviewUUID = ref("")

// 生成 UUID
const generateUUID = () => {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(
    /[xy]/g,
    function (c) {
      const r = (Math.random() * 16) | 0
      const v = c == "x" ? r : (r & 0x3) | 0x8
      return v.toString(16)
    }
  )
}

const handleReset = () => {
  searchInputStr.value = ""
  selectedStore.value = null
  pagesToFetch.value = 1
  storeData.value = []
  reviews.value = []
  searchUUID.value = ""
  reviewUUID.value = ""
}

const handleSearch = async () => {
  isLoading.value = true
  console.log(searchInputStr.value)
  if (searchInputStr.value === "") {
    alert("請輸入搜尋關鍵字")
    isLoading.value = false
    return
  }

  // 生成新的 UUID
  searchUUID.value = generateUUID()

  try {
    await pollForSearchResults()
  } catch (e) {
    console.error(e)
    alert("無法取得搜尋結果")
    isLoading.value = false
  }
}

const pollForSearchResults = async () => {
  try {
    const res = await fetch(
      searchStoreUrl + `?storeName=${searchInputStr.value}&uuid=${searchUUID.value}`
    )
    if (!res.ok) {
      console.error("Error:", res.statusText)
      alert("無法取得搜尋結果")
      isLoading.value = false
      return
    }

    const data = await res.json()
    console.log("Search response:", data)

    // 如果收到空陣列，表示正在查詢中，需要輪詢
    if (Array.isArray(data) && data.length === 0) {
      setTimeout(pollForSearchResults, 1000) // 1秒後重新查詢
      return
    }

    // 如果收到資料，表示查詢完成
    if (Array.isArray(data) && data.length > 0) {
      storeData.value = data
      if (storeData.value.length > 0) {
        selectedStore.value = storeData.value[0]
      }
      isLoading.value = false
      return
    }

    // 如果收到 null 或其他錯誤，表示查詢失敗
    alert("搜尋失敗")
    isLoading.value = false
  } catch (e) {
    console.error(e)
    alert("無法取得搜尋結果")
    isLoading.value = false
  }
}

const handleGetReview = async () => {
  isLoading.value = true
  console.log(selectedStore.value)
  if (!selectedStore.value || selectedStore.value === "") {
    alert("請選擇店家")
    isLoading.value = false
    return
  }

  // 生成新的 UUID
  reviewUUID.value = generateUUID()

  try {
    await pollForReviewResults()
  } catch (e) {
    console.error(e)
    alert("無法取得評論")
    isLoading.value = false
  }
}

const pollForReviewResults = async () => {
  try {
    const res = await fetch(
      getReviewsUrl +
      `?storeID=${selectedStore.value.ID}&pages=${pagesToFetch.value}&uuid=${reviewUUID.value}`
    )
    if (!res.ok) {
      console.error("Error:", res.statusText)
      alert("無法取得評論")
      isLoading.value = false
      return
    }

    const data = await res.json()
    console.log("Review response:", data)

    // 如果收到 null，表示正在查詢中，需要輪詢
    if (data === null) {
      setTimeout(pollForReviewResults, 1000) // 1秒後重新查詢
      return
    }

    // 如果收到資料，表示查詢完成
    if (data && typeof data === "object") {
      reviews.value = data
      isLoading.value = false
      return
    }

    // 其他情況表示查詢失敗
    alert("取得評論失敗")
    isLoading.value = false
  } catch (e) {
    console.error(e)
    alert("無法取得評論")
    isLoading.value = false
  }
}

const download = (type: string) => {
  const a = document.createElement("a")
  let url = ""
  switch (type) {
    case "csv":
      // 添加 BOM 標記
      const BOM = new Uint8Array([0xef, 0xbb, 0xbf])
      // 建立 CSV 內容，加入標題列
      const headers = Object.keys(reviews.value[0]).join(",")
      const rows = reviews.value.map((row: any) =>
        Object.values(row)
          .map((value: any) => {
            // 處理數值、字串中的特殊字元
            if (typeof value === "string") {
              // 如果內容包含逗號、換行或雙引號，就用雙引號包起來
              if (
                value.includes(",") ||
                value.includes("\n") ||
                value.includes('"')
              ) {
                return `"${value.replace(/"/g, '""')}"`
              }
            }
            return value
          })
          .join(",")
      )
      const csvContent = headers + "\n" + rows.join("\n")

      // 合併 BOM 和 CSV 內容
      const csvBlob = new Blob([BOM, csvContent], {
        type: "text/csv;charset=utf-8",
      })
      url = window.URL.createObjectURL(csvBlob)

      a.href = url
      a.download = `${selectedStore.value.Name}.csv`
      a.click()
      break
    case "json":
      const json = JSON.stringify(reviews.value, null, 2)
      const jsonBlob = new Blob([json], {
        type: "application/json;charset=utf-8",
      })
      url = window.URL.createObjectURL(jsonBlob)
      a.href = url
      a.download = `${selectedStore.value.Name}.json`
      a.click()
      break
    default:
      break
  }
  window.URL.revokeObjectURL(url)
}

onMounted(async () => {
  // Set document title
  document.title = `${props.title} - 榛果繽紛樂`
  // getNavbar() - 原本的 Svelte 代碼中有這個函數，但在提供的代碼中沒有定義
})
</script>

<template>
  <Layout>
    <div class="container">
      <img src="https://src.hazelnut-paradise.com/GooMapReviewSnatcher.png" alt="GooMapReviewSnatcher"
        style="width: 100%; max-width: 150px;" />
      <div class="title-box">
        <h1 class="title">{{ props.title }}</h1>
        <h2 class="subtitle">{{ props.subtitle }}</h2>
      </div>
      <Loader v-if="isLoading" />
      <InputCard v-else-if="reviews.length === 0" :search-input-str="searchInputStr" :selected-store="selectedStore"
        :store-data="storeData" :pages-to-fetch="pagesToFetch" :handle-search="handleSearch"
        :handle-get-review="handleGetReview" @update:search-input-str="searchInputStr = $event"
        @update:selected-store="selectedStore = $event" @update:store-data="storeData = $event"
        @update:pages-to-fetch="pagesToFetch = $event" />
      <Result v-else :reviews="reviews" :selected-store="selectedStore" :download="download" :handle-reset="handleReset"
        @update:reviews="reviews = $event" />
    </div>
  </Layout>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding-top: 20px;
  padding-bottom: 20px;
  /* background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); */
}

.title-box {
  display: flex;
  flex-direction: column;
  align-items: start;
  justify-content: center;
  margin-bottom: 1rem;
  transition: transform 0.3s ease;
}

.title {
  font-size: 2.5rem;
  color: #2c3e50;
  margin: 0;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
}

.title-box:hover {
  transform: scale(1.05);
}

.subtitle {
  font-size: 1.5rem;
  color: #0a0903;
  margin: 0;
}

@keyframes pop {
  0% {
    transform: scale(1);
  }

  50% {
    transform: scale(1.1);
  }

  100% {
    transform: scale(1);
  }
}
</style>

// src/pages/App.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import InputCard from '../components/InputCard.svelte'
    import Loader from '../components/Loader.svelte'
    export let title: string
    export let subtitle: string
    const searchStoreUrl = "/api/search";
    const getReviewsUrl = "/api/reviews";
    let searchInputStr = '';
    let selectedStore = '';
    let pagesToFetch = 1;
    let storeData = [];
    let reviews = [];

    let isLoading = false;
    const handleSearch = async() => {
        isLoading = true;
        console.log(searchInputStr);
        if (searchInputStr === "") {
            alert('請輸入搜尋關鍵字');
            isLoading = false;
            return;
        }
        try{
            const res = await fetch(searchStoreUrl+`?storeName=${searchInputStr}`);
            if (!res.ok) {
                console.error('Error:', res.statusText);
                alert('無法取得搜尋結果');
                return;
            }
            storeData = await res.json();
            console.log(storeData);
        }catch(e){
            console.error(e);
            alert('無法取得搜尋結果');
        }finally {
            isLoading = false;
        }
    }
    const handleGetReview = async() => {
        isLoading = true;
        console.log(selectedStore);
        if (selectedStore === "") {
            alert('請選擇店家');
            isLoading = false;
            return;
        }
        try{
            const res = await fetch(getReviewsUrl+`?storeID=${selectedStore.ID}&pages=${pagesToFetch}`);
            if (!res.ok) {
                console.error('Error:', res.statusText);
                alert('無法取得評論');
                return;
            }
            reviews = await res.json();
            console.log(reviews);
        }catch(e){
            console.error(e);
            alert('無法取得評論');
        }finally {
            isLoading = false;
        }
    }

    const download = (type) => {
        const a = document.createElement("a");
        let url = "";
        switch (type) {
            case "csv":
                // 添加 BOM 標記
                const BOM = new Uint8Array([0xEF, 0xBB, 0xBF]);
                // 建立 CSV 內容，加入標題列
                const headers = Object.keys(reviews[0]).join(',');
                const rows = reviews.map(row => 
                    Object.values(row)
                        .map(value => {
                            // 處理數值、字串中的特殊字元
                            if (typeof value === 'string') {
                                // 如果內容包含逗號、換行或雙引號，就用雙引號包起來
                                if (value.includes(',') || value.includes('\n') || value.includes('"')) {
                                    return `"${value.replace(/"/g, '""')}"`;
                                }
                            }
                            return value;
                        })
                        .join(',')
                );
                const csvContent = headers + '\n' + rows.join('\n');
                
                // 合併 BOM 和 CSV 內容
                const csvBlob = new Blob([BOM, csvContent], { type: 'text/csv;charset=utf-8' });
                url = window.URL.createObjectURL(csvBlob);
                
                a.href = url;
                a.download = `${selectedStore.Name}.csv`;
                a.click();
                break;
            case "json":
                const json = JSON.stringify(reviews, null, 2);
                const jsonBlob = new Blob([json], { type: 'application/json;charset=utf-8' });
                url = window.URL.createObjectURL(jsonBlob);
                a.href = url;
                a.download = `${selectedStore.Name}.json`;
                a.click();
                break;
            default:
                break;
        }
        window.URL.revokeObjectURL(url);
    }

    onMount(async () => {
        getNavbar();
    });
</script>

<svelte:head>
    <title>{title} - 榛果繽紛樂</title>
</svelte:head>

<div id="navbar-placeholder" style="height: 50px;"></div>
<div class="container">
    <img src="https://src.hazelnut-paradise.com/GooMapReviewSnatcher.png" alt="GooMapReviewSnatcher" style="width: 100%; max-width: 150px;"/>
    <div class="title-box">
        <h1 class="title">{title}</h1>
        <h2 class="subtitle">{subtitle}</h2>
    </div>
    {#if isLoading}
        <Loader/>
    {:else if Object.keys(reviews).length == 0}
    <InputCard
        bind:pagesToFetch
        bind:searchInputStr
        bind:selectedStore
        {handleSearch}
        {handleGetReview}
        {storeData}
    />
    {:else}
    <button class="reset-button button" on:click={()=> {
        searchInputStr = '';
        storeData = [];
        reviews = [];
    }}>查詢其他商家</button>
    <div class="review-box">
        <h3 class="store-name">{selectedStore.Name}</h3>
        <button class="download-button button" on:click={() => download("csv")}>下載 CSV</button>
        <button class="download-button button" on:click={() => download("json")}>下載 JSON</button>
        <div class="review-table-box">
            <table class="review-table">
                <thead>
                    <tr>
                    {#each Object.keys(reviews[0]) as key}
                        <th>{key}</th>
                    {/each}
                    </tr>
                </thead>
                <tbody>
                    {#each reviews as review}
                        <tr>
                            {#each Object.values(review) as value}
                                <td>{value}</td>
                            {/each}
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    </div>
    {/if}
</div>
<footer>
    2025 - 榛果繽紛樂
</footer>

<style>
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        padding-top: 20px;
        padding-bottom: 70px;
        /* background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); */
    }

    .title-box {
        display: flex;
        flex-direction: column;
        align-items: start;
        justify-content: center;
        margin-bottom: 1rem;
        transition: transform 0.3s ease;
    }

    .title {
        font-size: 2.5rem;
        color: #2c3e50;
        margin: 0;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
    }

    .title-box:hover {
        transform: scale(1.05);
    }

    .subtitle {
        font-size: 1.5rem;
        color: #0A0903;
        margin: 0;
    }

    .review-box {
        width: 80%;
    }

    .store-name {
        font-size: 1.5rem;
    }

    .review-table {
        border-collapse: collapse;
        width: 100%;
        background-color: white;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        overflow: hidden;
    }

    .review-table th {
        background-color: #2c3e50;
        color: white;
        padding: 12px 15px;
        text-align: left;
        font-weight: 600;
    }

    .review-table td {
        padding: 12px 15px;
        border-bottom: 1px solid #ddd;
    }

    .review-table tbody tr:hover {
        background-color: #f5f5f5;
        transition: background-color 0.2s ease;
    }

    .review-table tbody tr:last-child td {
        border-bottom: none;
    }

    .review-table-box {
        width: 100%;
        height: 500px;
        overflow: auto;
        background-color: white;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        padding: 1rem;
    }

    /* 美化捲軸 */
    .review-table-box::-webkit-scrollbar {
        width: 8px;
        height: 8px;
    }

    .review-table-box::-webkit-scrollbar-track {
        background: #f1f1f1;
        border-radius: 4px;
    }

    .review-table-box::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 4px;
    }

    .review-table-box::-webkit-scrollbar-thumb:hover {
        background: #555;
    }

    .reset-button {
        height: 50px;
        width: 20%;
        min-width: 200px;
        border-radius: 15px;
        border: none;
        background-color: #0A0903;
        color: white;
        font-size: 1rem;
        cursor: pointer;
        margin-bottom: 1rem;
    }

    .download-button {
        height: 40px;
        width: 20%;
        min-width: 200px;
        border-radius: 15px;
        border: none;
        background-color: #0A0903;
        color: white;
        font-size: 1rem;
        cursor: pointer;
        margin-bottom: 1rem;
    }

    footer {
        width: 100vw;
        height: 50px;
        background-color: #0A0903;
        color: white;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .button:hover {
        background-color: #f1f1f1;
        color: #0A0903;
    }

    @keyframes pop {
        0% { transform: scale(1); }
        50% { transform: scale(1.1); }
        100% { transform: scale(1); }
    }
</style>
